### PR TITLE
The generated nuget package does not copy the AceEditor.Zip into modules

### LINKED ISSUE #13: Nuget package is missing the AceEditor.zip
When using the generated nuget package, the AceEditor.zip is not included in the modules folder.

It looks like the csproj file needs to include PackageCopyToOutput=true and that the Reference to AceEditor.targets is not correct

### PR DESCRIPTION
**Pull request by anderstoft**
When using the generated nuget package, it looks like the AceEditor.zip is not included in the modules folder.
This is now added by including PackageCopyToOutput=true to the csproj file.

Reference to AceEditor.targets is also fixed.

Fixes #13

### CODE REVIEW

**Comment by anderstoft** [comment]
Hi @chrno1209 and @davidknipe,
I've created this PR because I'm experiencing issues when using the Nuget package.

**Comment by chrno1209** [comment]
As I left Episerver for years and no chance to get my hands on the CMS itself, so @davidknipe can you maintain the project?

**Comment by OMGPizzaGuy** [comment]
@chrno1209 - If you're interested, I am willing to maintain the project.

**Comment by OMGPizzaGuy** [comment]
It appears PackageCopyToOutput is needed. I was able to build & debug without but failed to run a published version.

**Comment by schliemann** [comment]
@OMGPizzaGuy Have you been added as contributor yet?

**Comment by OMGPizzaGuy** [comment]
@schliemann - I've been added and created a release, however I think this may still be an issue. Currently investigating again

**Comment by OMGPizzaGuy** [comment]
Adjusted for conflicts and merging. Thank you!

**Pull request merged**
